2021-02-20 20:53:09,932 - INFO - 
Config:
'add_train': False
'batch_size': 64
'continue_flag': ''
'cur_time': '2021_02_20_20_53_00'
'debug_mode': False
'debug_num': 500
'do_continue_train': False
'do_figure_save': False
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 20
'feature_columns': [2, 3, 4, 5, 6, 7, 8]
'figure_save_path': './figure/'
'hidden_size': 128
'input_size': 7
'label_columns': [4, 5]
'label_in_feature_index': [2, 3]
'learning_rate': 0.001
'log_save_path': './log/2021_02_20_20_53_00_keras/'
'lstm_layers': 2
'model_name': 'model_keras.h5'
'model_postfix': {'pytorch': '.pth'
'keras': '.h5'
'tensorflow': '.ckpt'}
'model_save_path': './checkpoint/keras/'
'output_size': 2
'patience': 5
'predict_day': 1
'random_seed': 42
'shuffle_train_data': True
'time_step': 20
'train_data_path': './data/stock_data.csv'
'train_data_rate': 0.95
'use_cuda': False
'used_frame': 'keras'
'valid_data_rate': 0.15
2021-02-20 20:53:29,626 - ERROR - Run Error
Traceback (most recent call last):
  File "D:\Python Projects\LearnNotes\keras_stock_lstm\keras_stock_lstm\keras_stock_lstm.py", line 250, in main
    train_X, valid_X, train_Y, valid_Y = data_gainer.get_train_and_valid_data()
  File "D:\Python Projects\LearnNotes\keras_stock_lstm\keras_stock_lstm\keras_stock_lstm.py", line 135, in get_train_and_valid_data
    print(list_shape.shape)
AttributeError: 'tuple' object has no attribute 'shape'
